version: '3.8'

services:
  # mysql
  mysql-db:
    image: mysql:8.0.29
    container_name: mysql
    restart: always
    volumes:
      - ./member-app/db_data/member.sql:/docker-entrypoint-initdb.d/member.sql
      - ./member-app/mysql/:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: sanyabot42
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - mysql-db
    image: phpmyadmin/phpmyadmin:5.1.3
    container_name: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql-db
      MYSQL_ROOT_PASSWORD: sanyabot42
  # app
  my_app:
    depends_on:
      - mysql-db
    container_name: node_member
    build: ./member-app
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true